name: vaccine_home
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.11
  device_preview: ^1.2.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  dio: ^5.9.0
  get_it: ^8.2.0
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/local/
