name: vaccine_home
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.11
  device_preview: ^1.2.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  dio: ^5.9.0
  get_it: ^8.2.0
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  googleapis_auth: ^1.6.0
  http: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_markdown: ^0.7.7+1
  carousel_slider: ^5.1.1
  youtube_player_flutter: ^9.1.2
  percent_indicator: ^4.2.5
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/local/
    - assets/images/logos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logos/app_logo.png"
  adaptive_icon_background: "#F5E6FE"
